(ns aws.certificate-manager
  "AUTOGENERATED clojure.spec definitions"
  (:require [clojure.spec.alpha]))

(clojure.spec.alpha/def
 :aws.certificate-manager/certificate
 (clojure.spec.alpha/keys
  :req
  [:aws.certificate-manager/domain-name]
  :opt
  [:aws.certificate-manager/domain-validation-options
   :aws.certificate-manager/subject-alternative-names
   :aws.certificate-manager/tags]))
(do
 (clojure.spec.alpha/def
  :aws.certificate-manager/domain-name
  clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.certificate-manager/validation-domain
  clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.certificate-manager/domain-validation-option
  (clojure.spec.alpha/keys
   :req
   [:aws.certificate-manager/domain-name
    :aws.certificate-manager/validation-domain]
   :opt
   [])))
