(ns aws.cloud-formation
  "AUTOGENERATED clojure.spec definitions"
  (:require [clojure.spec.alpha]))

(clojure.spec.alpha/def
 :aws.cloud-formation/custom-resource
 (clojure.spec.alpha/keys
  :req
  [:aws.cloud-formation/service-token]
  :opt
  []))
(clojure.spec.alpha/def
 :aws.cloud-formation/wait-condition-handle
 (clojure.spec.alpha/keys :req [] :opt []))
(clojure.spec.alpha/def
 :aws.cloud-formation/stack
 (clojure.spec.alpha/keys
  :req
  [:aws.cloud-formation/template-url]
  :opt
  [:aws.cloud-formation/notification-ar-ns
   :aws.cloud-formation/parameters
   :aws.cloud-formation/tags
   :aws.cloud-formation/timeout-in-minutes]))
(clojure.spec.alpha/def
 :aws.cloud-formation/wait-condition
 (clojure.spec.alpha/keys
  :req
  [:aws.cloud-formation/handle :aws.cloud-formation/timeout]
  :opt
  [:aws.cloud-formation/count]))
