(ns aws.code-pipeline
  "AUTOGENERATED clojure.spec definitions"
  (:require [clojure.spec.alpha]))

(clojure.spec.alpha/def
 :aws.code-pipeline/custom-action-type
 (clojure.spec.alpha/keys
  :req
  [:aws.code-pipeline/category
   :aws.code-pipeline/input-artifact-details
   :aws.code-pipeline/output-artifact-details
   :aws.code-pipeline/provider]
  :opt
  [:aws.code-pipeline/configuration-properties
   :aws.code-pipeline/settings
   :aws.code-pipeline/version]))
(clojure.spec.alpha/def
 :aws.code-pipeline/pipeline
 (clojure.spec.alpha/keys
  :req
  [:aws.code-pipeline/artifact-store
   :aws.code-pipeline/role-arn
   :aws.code-pipeline/stages]
  :opt
  [:aws.code-pipeline/disable-inbound-stage-transitions
   :aws.code-pipeline/name
   :aws.code-pipeline/restart-execution-on-update]))
(do
 (clojure.spec.alpha/def
  :aws.code-pipeline/category
  clojure.core/string?)
 (clojure.spec.alpha/def :aws.code-pipeline/owner clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.code-pipeline/provider
  clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.code-pipeline/version
  clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.code-pipeline/action-type-id
  (clojure.spec.alpha/keys
   :req
   [:aws.code-pipeline/category
    :aws.code-pipeline/owner
    :aws.code-pipeline/provider
    :aws.code-pipeline/version]
   :opt
   [])))
(do
 (clojure.spec.alpha/def
  :aws.code-pipeline/maximum-count
  clojure.core/integer?)
 (clojure.spec.alpha/def
  :aws.code-pipeline/minimum-count
  clojure.core/integer?)
 (clojure.spec.alpha/def
  :aws.code-pipeline/artifact-details
  (clojure.spec.alpha/keys
   :req
   [:aws.code-pipeline/maximum-count :aws.code-pipeline/minimum-count]
   :opt
   [])))
(do
 (clojure.spec.alpha/def :aws.code-pipeline/name clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.code-pipeline/output-artifact
  (clojure.spec.alpha/keys :req [:aws.code-pipeline/name] :opt [])))
(do
 (clojure.spec.alpha/def
  :aws.code-pipeline/entity-url-template
  clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.code-pipeline/execution-url-template
  clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.code-pipeline/revision-url-template
  clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.code-pipeline/third-party-configuration-url
  clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.code-pipeline/settings
  (clojure.spec.alpha/keys
   :req
   []
   :opt
   [:aws.code-pipeline/entity-url-template
    :aws.code-pipeline/execution-url-template
    :aws.code-pipeline/revision-url-template
    :aws.code-pipeline/third-party-configuration-url])))
(do
 (clojure.spec.alpha/def
  :aws.code-pipeline/reason
  clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.code-pipeline/stage-name
  clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.code-pipeline/stage-transition
  (clojure.spec.alpha/keys
   :req
   [:aws.code-pipeline/reason :aws.code-pipeline/stage-name]
   :opt
   [])))
(do
 (clojure.spec.alpha/def
  :aws.code-pipeline/description
  clojure.core/string?)
 (clojure.spec.alpha/def :aws.code-pipeline/key clojure.core/boolean?)
 (clojure.spec.alpha/def :aws.code-pipeline/name clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.code-pipeline/queryable
  clojure.core/boolean?)
 (clojure.spec.alpha/def
  :aws.code-pipeline/required
  clojure.core/boolean?)
 (clojure.spec.alpha/def
  :aws.code-pipeline/secret
  clojure.core/boolean?)
 (clojure.spec.alpha/def :aws.code-pipeline/type clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.code-pipeline/configuration-properties
  (clojure.spec.alpha/keys
   :req
   [:aws.code-pipeline/key
    :aws.code-pipeline/name
    :aws.code-pipeline/required
    :aws.code-pipeline/secret]
   :opt
   [:aws.code-pipeline/description
    :aws.code-pipeline/queryable
    :aws.code-pipeline/type])))
(do
 (clojure.spec.alpha/def :aws.code-pipeline/name clojure.core/string?)
 (clojure.spec.alpha/def :aws.code-pipeline/type clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.code-pipeline/blocker-declaration
  (clojure.spec.alpha/keys
   :req
   [:aws.code-pipeline/name :aws.code-pipeline/type]
   :opt
   [])))
(do
 (clojure.spec.alpha/def :aws.code-pipeline/name clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.code-pipeline/input-artifact
  (clojure.spec.alpha/keys :req [:aws.code-pipeline/name] :opt [])))
(do
 (clojure.spec.alpha/def
  :aws.code-pipeline/configuration
  clojure.core/any?)
 (clojure.spec.alpha/def :aws.code-pipeline/name clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.code-pipeline/role-arn
  clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.code-pipeline/run-order
  clojure.core/integer?)
 (clojure.spec.alpha/def
  :aws.code-pipeline/action-declaration
  (clojure.spec.alpha/keys
   :req
   [:aws.code-pipeline/action-type-id :aws.code-pipeline/name]
   :opt
   [:aws.code-pipeline/configuration
    :aws.code-pipeline/input-artifacts
    :aws.code-pipeline/output-artifacts
    :aws.code-pipeline/role-arn
    :aws.code-pipeline/run-order])))
(do
 (clojure.spec.alpha/def
  :aws.code-pipeline/location
  clojure.core/string?)
 (clojure.spec.alpha/def :aws.code-pipeline/type clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.code-pipeline/artifact-store
  (clojure.spec.alpha/keys
   :req
   [:aws.code-pipeline/location :aws.code-pipeline/type]
   :opt
   [:aws.code-pipeline/encryption-key])))
(do
 (clojure.spec.alpha/def :aws.code-pipeline/name clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.code-pipeline/stage-declaration
  (clojure.spec.alpha/keys
   :req
   [:aws.code-pipeline/actions :aws.code-pipeline/name]
   :opt
   [:aws.code-pipeline/blockers])))
(do
 (clojure.spec.alpha/def :aws.code-pipeline/id clojure.core/string?)
 (clojure.spec.alpha/def :aws.code-pipeline/type clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.code-pipeline/encryption-key
  (clojure.spec.alpha/keys
   :req
   [:aws.code-pipeline/id :aws.code-pipeline/type]
   :opt
   [])))
