(ns aws.config
  "AUTOGENERATED clojure.spec definitions"
  (:require [clojure.spec.alpha]
            [edn-to-cfn.specs.cfn :as cfn-specs]))

(do
 (clojure.core/defmethod
  cfn-specs/resource-type-spec
  :aws.config/configuration-recorder
  [___16342__auto__]
  (clojure.spec.alpha/keys
   :req
   [:aws.config/role-arn]
   :opt
   [:aws.config/name :aws.config/recording-group]))
 (clojure.spec.alpha/def :aws.config/name clojure.core/string?)
 (clojure.spec.alpha/def :aws.config/role-arn clojure.core/string?))
(do
 (clojure.core/defmethod
  cfn-specs/resource-type-spec
  :aws.config/config-rule
  [___16342__auto__]
  (clojure.spec.alpha/keys
   :req
   [:aws.config/source]
   :opt
   [:aws.config/config-rule-name
    :aws.config/description
    :aws.config/input-parameters
    :aws.config/maximum-execution-frequency
    :aws.config/scope]))
 (clojure.spec.alpha/def
  :aws.config/config-rule-name
  clojure.core/string?)
 (clojure.spec.alpha/def :aws.config/description clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.config/input-parameters
  clojure.core/any?)
 (clojure.spec.alpha/def
  :aws.config/maximum-execution-frequency
  clojure.core/string?))
(do
 (clojure.core/defmethod
  cfn-specs/resource-type-spec
  :aws.config/delivery-channel
  [___16342__auto__]
  (clojure.spec.alpha/keys
   :req
   [:aws.config/s3-bucket-name]
   :opt
   [:aws.config/config-snapshot-delivery-properties
    :aws.config/name
    :aws.config/s3-key-prefix
    :aws.config/sns-topic-arn]))
 (clojure.spec.alpha/def :aws.config/name clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.config/s3-bucket-name
  clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.config/s3-key-prefix
  clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.config/sns-topic-arn
  clojure.core/string?))
(do
 (clojure.spec.alpha/def
  :aws.config/compliance-resource-id
  clojure.core/string?)
 (clojure.spec.alpha/def :aws.config/tag-key clojure.core/string?)
 (clojure.spec.alpha/def :aws.config/tag-value clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.config/scope
  (clojure.spec.alpha/keys
   :req
   []
   :opt
   [:aws.config/compliance-resource-id
    :aws.config/compliance-resource-types
    :aws.config/tag-key
    :aws.config/tag-value])))
(do
 (clojure.spec.alpha/def :aws.config/event-source clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.config/maximum-execution-frequency
  clojure.core/string?)
 (clojure.spec.alpha/def :aws.config/message-type clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.config/source-detail
  (clojure.spec.alpha/keys
   :req
   [:aws.config/event-source :aws.config/message-type]
   :opt
   [:aws.config/maximum-execution-frequency])))
(do
 (clojure.spec.alpha/def :aws.config/owner clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.config/source-identifier
  clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.config/source
  (clojure.spec.alpha/keys
   :req
   [:aws.config/owner :aws.config/source-identifier]
   :opt
   [:aws.config/source-details])))
(do
 (clojure.spec.alpha/def
  :aws.config/delivery-frequency
  clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.config/config-snapshot-delivery-properties
  (clojure.spec.alpha/keys
   :req
   []
   :opt
   [:aws.config/delivery-frequency])))
(do
 (clojure.spec.alpha/def
  :aws.config/all-supported
  clojure.core/boolean?)
 (clojure.spec.alpha/def
  :aws.config/include-global-resource-types
  clojure.core/boolean?)
 (clojure.spec.alpha/def
  :aws.config/recording-group
  (clojure.spec.alpha/keys
   :req
   []
   :opt
   [:aws.config/all-supported
    :aws.config/include-global-resource-types
    :aws.config/resource-types])))
