(ns aws.ecr
  "AUTOGENERATED clojure.spec definitions"
  (:require [clojure.spec.alpha]
            [edn-to-cfn.specs.cfn :as cfn-specs]))

(do
 (clojure.core/defmethod
  cfn-specs/resource-type-spec
  :aws.ecr/repository
  [___16342__auto__]
  (clojure.spec.alpha/keys
   :req
   []
   :opt
   [:aws.ecr/lifecycle-policy
    :aws.ecr/repository-name
    :aws.ecr/repository-policy-text]))
 (clojure.spec.alpha/def :aws.ecr/repository-name clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.ecr/repository-policy-text
  clojure.core/any?))
(do
 (clojure.spec.alpha/def
  :aws.ecr/lifecycle-policy-text
  clojure.core/string?)
 (clojure.spec.alpha/def :aws.ecr/registry-id clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.ecr/lifecycle-policy
  (clojure.spec.alpha/keys
   :req
   []
   :opt
   [:aws.ecr/lifecycle-policy-text :aws.ecr/registry-id])))
