(ns aws.efs
  "AUTOGENERATED clojure.spec definitions"
  (:require [clojure.spec.alpha]
            [edn-to-cfn.specs.cfn :as cfn-specs]))

(do
 (clojure.core/defmethod
  cfn-specs/resource-type-spec
  :aws.efs/mount-target
  [___16342__auto__]
  (clojure.spec.alpha/keys
   :req
   [:aws.efs/file-system-id
    :aws.efs/security-groups
    :aws.efs/subnet-id]
   :opt
   [:aws.efs/ip-address]))
 (clojure.spec.alpha/def :aws.efs/file-system-id clojure.core/string?)
 (clojure.spec.alpha/def :aws.efs/ip-address clojure.core/string?)
 (clojure.spec.alpha/def :aws.efs/subnet-id clojure.core/string?))
(do
 (clojure.core/defmethod
  cfn-specs/resource-type-spec
  :aws.efs/file-system
  [___16342__auto__]
  (clojure.spec.alpha/keys
   :req
   []
   :opt
   [:aws.efs/encrypted
    :aws.efs/file-system-tags
    :aws.efs/kms-key-id
    :aws.efs/performance-mode]))
 (clojure.spec.alpha/def :aws.efs/encrypted clojure.core/boolean?)
 (clojure.spec.alpha/def :aws.efs/kms-key-id clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.efs/performance-mode
  clojure.core/string?))
(do
 (clojure.spec.alpha/def :aws.efs/key clojure.core/string?)
 (clojure.spec.alpha/def :aws.efs/value clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.efs/elastic-file-system-tag
  (clojure.spec.alpha/keys :req [:aws.efs/key :aws.efs/value] :opt [])))
