(ns aws.efs
  "AUTOGENERATED clojure.spec definitions"
  (:require [clojure.spec.alpha]))

(clojure.spec.alpha/def
 :aws.efs/mount-target
 (clojure.spec.alpha/keys
  :req
  [:aws.efs/file-system-id :aws.efs/security-groups :aws.efs/subnet-id]
  :opt
  [:aws.efs/ip-address]))
(clojure.spec.alpha/def
 :aws.efs/file-system
 (clojure.spec.alpha/keys
  :req
  []
  :opt
  [:aws.efs/encrypted
   :aws.efs/file-system-tags
   :aws.efs/kms-key-id
   :aws.efs/performance-mode]))
(do
 (clojure.spec.alpha/def :aws.efs/key clojure.core/string?)
 (clojure.spec.alpha/def :aws.efs/value clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.efs/elastic-file-system-tag
  (clojure.spec.alpha/keys :req [:aws.efs/key :aws.efs/value] :opt [])))
