(ns aws.guard-duty
  "AUTOGENERATED clojure.spec definitions"
  (:require [clojure.spec.alpha]))

(clojure.spec.alpha/def
 :aws.guard-duty/member
 (clojure.spec.alpha/keys
  :req
  [:aws.guard-duty/member-id
   :aws.guard-duty/email
   :aws.guard-duty/detector-id]
  :opt
  [:aws.guard-duty/status :aws.guard-duty/message]))
(clojure.spec.alpha/def
 :aws.guard-duty/threat-intel-set
 (clojure.spec.alpha/keys
  :req
  [:aws.guard-duty/format
   :aws.guard-duty/activate
   :aws.guard-duty/detector-id
   :aws.guard-duty/location]
  :opt
  [:aws.guard-duty/name]))
(clojure.spec.alpha/def
 :aws.guard-duty/master
 (clojure.spec.alpha/keys
  :req
  [:aws.guard-duty/detector-id
   :aws.guard-duty/master-id
   :aws.guard-duty/invitation-id]
  :opt
  []))
(clojure.spec.alpha/def
 :aws.guard-duty/detector
 (clojure.spec.alpha/keys :req [:aws.guard-duty/enable] :opt []))
(clojure.spec.alpha/def
 :aws.guard-duty/ip-set
 (clojure.spec.alpha/keys
  :req
  [:aws.guard-duty/format
   :aws.guard-duty/activate
   :aws.guard-duty/detector-id
   :aws.guard-duty/location]
  :opt
  [:aws.guard-duty/name]))
