(ns aws.kinesis
  "AUTOGENERATED clojure.spec definitions"
  (:require [clojure.spec.alpha]
            [edn-to-cfn.specs.cfn :as cfn-specs]))

(do
 (clojure.core/defmethod
  cfn-specs/resource-type-spec
  :aws.kinesis/stream
  [___16342__auto__]
  (clojure.spec.alpha/keys
   :req
   [:aws.kinesis/shard-count]
   :opt
   [:aws.kinesis/name
    :aws.kinesis/retention-period-hours
    :aws.kinesis/stream-encryption
    :aws.kinesis/tags]))
 (clojure.spec.alpha/def :aws.kinesis/name clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.kinesis/retention-period-hours
  clojure.core/integer?)
 (clojure.spec.alpha/def
  :aws.kinesis/shard-count
  clojure.core/integer?))
(do
 (clojure.spec.alpha/def
  :aws.kinesis/encryption-type
  clojure.core/string?)
 (clojure.spec.alpha/def :aws.kinesis/key-id clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.kinesis/stream-encryption
  (clojure.spec.alpha/keys
   :req
   [:aws.kinesis/encryption-type :aws.kinesis/key-id]
   :opt
   [])))
