(ns aws.kinesis
  "AUTOGENERATED clojure.spec definitions"
  (:require [clojure.spec.alpha]))

(clojure.spec.alpha/def
 :aws.kinesis/stream
 (clojure.spec.alpha/keys
  :req
  [:aws.kinesis/shard-count]
  :opt
  [:aws.kinesis/name
   :aws.kinesis/retention-period-hours
   :aws.kinesis/stream-encryption
   :aws.kinesis/tags]))
(do
 (clojure.spec.alpha/def
  :aws.kinesis/encryption-type
  clojure.core/string?)
 (clojure.spec.alpha/def :aws.kinesis/key-id clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.kinesis/stream-encryption
  (clojure.spec.alpha/keys
   :req
   [:aws.kinesis/encryption-type :aws.kinesis/key-id]
   :opt
   [])))
