(ns aws.kms
  "AUTOGENERATED clojure.spec definitions"
  (:require [clojure.spec.alpha]
            [edn-to-cfn.specs.cfn :as cfn-specs]))

(do
 (clojure.core/defmethod
  cfn-specs/resource-type-spec
  :aws.kms/key
  [___16342__auto__]
  (clojure.spec.alpha/keys
   :req
   [:aws.kms/key-policy]
   :opt
   [:aws.kms/description
    :aws.kms/enable-key-rotation
    :aws.kms/enabled
    :aws.kms/key-usage
    :aws.kms/tags]))
 (clojure.spec.alpha/def :aws.kms/description clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.kms/enable-key-rotation
  clojure.core/boolean?)
 (clojure.spec.alpha/def :aws.kms/enabled clojure.core/boolean?)
 (clojure.spec.alpha/def :aws.kms/key-policy clojure.core/any?)
 (clojure.spec.alpha/def :aws.kms/key-usage clojure.core/string?))
(do
 (clojure.core/defmethod
  cfn-specs/resource-type-spec
  :aws.kms/alias
  [___16342__auto__]
  (clojure.spec.alpha/keys
   :req
   [:aws.kms/alias-name :aws.kms/target-key-id]
   :opt
   []))
 (clojure.spec.alpha/def :aws.kms/alias-name clojure.core/string?)
 (clojure.spec.alpha/def :aws.kms/target-key-id clojure.core/string?))
