(ns aws.kms
  "AUTOGENERATED clojure.spec definitions"
  (:require [clojure.spec.alpha]))

(clojure.spec.alpha/def
 :aws.kms/key
 (clojure.spec.alpha/keys
  :req
  [:aws.kms/key-policy]
  :opt
  [:aws.kms/description
   :aws.kms/enable-key-rotation
   :aws.kms/enabled
   :aws.kms/key-usage
   :aws.kms/tags]))
(clojure.spec.alpha/def
 :aws.kms/alias
 (clojure.spec.alpha/keys
  :req
  [:aws.kms/alias-name :aws.kms/target-key-id]
  :opt
  []))
