(ns aws.sqs
  "AUTOGENERATED clojure.spec definitions"
  (:require [clojure.spec.alpha]))

(clojure.spec.alpha/def
 :aws.sqs/queue
 (clojure.spec.alpha/keys
  :req
  []
  :opt
  [:aws.sqs/delay-seconds
   :aws.sqs/fifo-queue
   :aws.sqs/content-based-deduplication
   :aws.sqs/redrive-policy
   :aws.sqs/queue-name
   :aws.sqs/kms-data-key-reuse-period-seconds
   :aws.sqs/message-retention-period
   :aws.sqs/visibility-timeout
   :aws.sqs/maximum-message-size
   :aws.sqs/receive-message-wait-time-seconds
   :aws.sqs/kms-master-key-id]))
(clojure.spec.alpha/def
 :aws.sqs/queue-policy
 (clojure.spec.alpha/keys
  :req
  [:aws.sqs/policy-document :aws.sqs/queues]
  :opt
  []))
