(ns aws.step-functions
  "AUTOGENERATED clojure.spec definitions"
  (:require [clojure.spec.alpha]
            [edn-to-cfn.specs.cfn :as cfn-specs]))

(do
 (clojure.core/defmethod
  cfn-specs/resource-type-spec
  :aws.step-functions/activity
  [___16342__auto__]
  (clojure.spec.alpha/keys :req [:aws.step-functions/name] :opt []))
 (clojure.spec.alpha/def :aws.step-functions/name clojure.core/string?))
(do
 (clojure.core/defmethod
  cfn-specs/resource-type-spec
  :aws.step-functions/state-machine
  [___16342__auto__]
  (clojure.spec.alpha/keys
   :req
   [:aws.step-functions/definition-string :aws.step-functions/role-arn]
   :opt
   [:aws.step-functions/state-machine-name]))
 (clojure.spec.alpha/def
  :aws.step-functions/definition-string
  clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.step-functions/state-machine-name
  clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.step-functions/role-arn
  clojure.core/string?))
