(ns aws.work-spaces
  "AUTOGENERATED clojure.spec definitions"
  (:require [clojure.spec.alpha]
            [edn-to-cfn.specs.cfn :as cfn-specs]))

(do
 (clojure.core/defmethod
  cfn-specs/resource-type-spec
  :aws.work-spaces/workspace
  [___16342__auto__]
  (clojure.spec.alpha/keys
   :req
   [:aws.work-spaces/bundle-id
    :aws.work-spaces/directory-id
    :aws.work-spaces/user-name]
   :opt
   [:aws.work-spaces/root-volume-encryption-enabled
    :aws.work-spaces/user-volume-encryption-enabled
    :aws.work-spaces/volume-encryption-key]))
 (clojure.spec.alpha/def
  :aws.work-spaces/bundle-id
  clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.work-spaces/directory-id
  clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.work-spaces/root-volume-encryption-enabled
  clojure.core/boolean?)
 (clojure.spec.alpha/def
  :aws.work-spaces/user-name
  clojure.core/string?)
 (clojure.spec.alpha/def
  :aws.work-spaces/user-volume-encryption-enabled
  clojure.core/boolean?)
 (clojure.spec.alpha/def
  :aws.work-spaces/volume-encryption-key
  clojure.core/string?))
