(ns portkey.cloudformation.application-auto-scaling
  "AUTOGENERATED clojure.spec definitions"
  (:require [clojure.spec.alpha]
            [portkey.cloudformation]))

(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.application-auto-scaling/scalable-target
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.application-auto-scaling/max-capacity
    :portkey.cloudformation.application-auto-scaling/min-capacity
    :portkey.cloudformation.application-auto-scaling/resource-id
    :portkey.cloudformation.application-auto-scaling/role-arn
    :portkey.cloudformation.application-auto-scaling/scalable-dimension
    :portkey.cloudformation.application-auto-scaling/service-namespace]
   :opt
   [:portkey.cloudformation.application-auto-scaling/scheduled-actions]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/max-capacity
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/min-capacity
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/resource-id
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/role-arn
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/scalable-dimension
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/service-namespace
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.application-auto-scaling/scaling-policy
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.application-auto-scaling/policy-name
    :portkey.cloudformation.application-auto-scaling/policy-type]
   :opt
   [:portkey.cloudformation.application-auto-scaling/resource-id
    :portkey.cloudformation.application-auto-scaling/scalable-dimension
    :portkey.cloudformation.application-auto-scaling/scaling-target-id
    :portkey.cloudformation.application-auto-scaling/service-namespace
    :portkey.cloudformation.application-auto-scaling/step-scaling-policy-configuration
    :portkey.cloudformation.application-auto-scaling/target-tracking-scaling-policy-configuration]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/policy-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/policy-type
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/resource-id
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/scalable-dimension
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/scaling-target-id
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/service-namespace
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/adjustment-type
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/cooldown
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/metric-aggregation-type
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/min-adjustment-magnitude
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/step-scaling-policy-configuration
  (clojure.spec.alpha/keys
   :req
   []
   :opt
   [:portkey.cloudformation.application-auto-scaling/adjustment-type
    :portkey.cloudformation.application-auto-scaling/cooldown
    :portkey.cloudformation.application-auto-scaling/metric-aggregation-type
    :portkey.cloudformation.application-auto-scaling/min-adjustment-magnitude
    :portkey.cloudformation.application-auto-scaling/step-adjustments])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/metric-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/namespace
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/statistic
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/unit
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/customized-metric-specification
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.application-auto-scaling/metric-name
    :portkey.cloudformation.application-auto-scaling/namespace
    :portkey.cloudformation.application-auto-scaling/statistic]
   :opt
   [:portkey.cloudformation.application-auto-scaling/dimensions
    :portkey.cloudformation.application-auto-scaling/unit])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/metric-interval-lower-bound
  (portkey.cloudformation/ref-or-spec clojure.core/double?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/metric-interval-upper-bound
  (portkey.cloudformation/ref-or-spec clojure.core/double?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/scaling-adjustment
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/step-adjustment
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.application-auto-scaling/scaling-adjustment]
   :opt
   [:portkey.cloudformation.application-auto-scaling/metric-interval-lower-bound
    :portkey.cloudformation.application-auto-scaling/metric-interval-upper-bound])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/end-time
  (portkey.cloudformation/ref-or-spec clojure.core/inst?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/schedule
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/scheduled-action-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/start-time
  (portkey.cloudformation/ref-or-spec clojure.core/inst?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/scheduled-action
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.application-auto-scaling/schedule
    :portkey.cloudformation.application-auto-scaling/scheduled-action-name]
   :opt
   [:portkey.cloudformation.application-auto-scaling/end-time
    :portkey.cloudformation.application-auto-scaling/scalable-target-action
    :portkey.cloudformation.application-auto-scaling/start-time])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/predefined-metric-type
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/resource-label
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/predefined-metric-specification
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.application-auto-scaling/predefined-metric-type]
   :opt
   [:portkey.cloudformation.application-auto-scaling/resource-label])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/max-capacity
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/min-capacity
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/scalable-target-action
  (clojure.spec.alpha/keys
   :req
   []
   :opt
   [:portkey.cloudformation.application-auto-scaling/max-capacity
    :portkey.cloudformation.application-auto-scaling/min-capacity])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/disable-scale-in
  (portkey.cloudformation/ref-or-spec clojure.core/boolean?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/scale-in-cooldown
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/scale-out-cooldown
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/target-value
  (portkey.cloudformation/ref-or-spec clojure.core/double?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/target-tracking-scaling-policy-configuration
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.application-auto-scaling/target-value]
   :opt
   [:portkey.cloudformation.application-auto-scaling/customized-metric-specification
    :portkey.cloudformation.application-auto-scaling/disable-scale-in
    :portkey.cloudformation.application-auto-scaling/predefined-metric-specification
    :portkey.cloudformation.application-auto-scaling/scale-in-cooldown
    :portkey.cloudformation.application-auto-scaling/scale-out-cooldown])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/value
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.application-auto-scaling/metric-dimension
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.application-auto-scaling/name
    :portkey.cloudformation.application-auto-scaling/value]
   :opt
   [])))
