(ns portkey.cloudformation.cloud-formation
  "AUTOGENERATED clojure.spec definitions"
  (:require [clojure.spec.alpha]
            [portkey.cloudformation]))

(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.cloud-formation/custom-resource
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.cloud-formation/service-token]
   :opt
   []))
 (clojure.spec.alpha/def
  :portkey.cloudformation.cloud-formation/service-token
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.cloud-formation/wait-condition-handle
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id :portkey.cloudformation/type]
   :opt
   [])))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.cloud-formation/stack
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.cloud-formation/template-url]
   :opt
   [:portkey.cloudformation.cloud-formation/notification-ar-ns
    :portkey.cloudformation.cloud-formation/parameters
    :portkey.cloudformation.cloud-formation/tags
    :portkey.cloudformation.cloud-formation/timeout-in-minutes]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.cloud-formation/template-url
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.cloud-formation/timeout-in-minutes
  (portkey.cloudformation/ref-or-spec clojure.core/integer?)))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.cloud-formation/wait-condition
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.cloud-formation/handle
    :portkey.cloudformation.cloud-formation/timeout]
   :opt
   [:portkey.cloudformation.cloud-formation/count]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.cloud-formation/count
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.cloud-formation/handle
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.cloud-formation/timeout
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
