(ns portkey.cloudformation.dynamo-db
  "AUTOGENERATED clojure.spec definitions"
  (:require [clojure.spec.alpha]
            [portkey.cloudformation]))

(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.dynamo-db/table
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.dynamo-db/key-schema
    :portkey.cloudformation.dynamo-db/provisioned-throughput]
   :opt
   [:portkey.cloudformation.dynamo-db/stream-specification
    :portkey.cloudformation.dynamo-db/time-to-live-specification
    :portkey.cloudformation.dynamo-db/attribute-definitions
    :portkey.cloudformation.dynamo-db/tags
    :portkey.cloudformation.dynamo-db/local-secondary-indexes
    :portkey.cloudformation.dynamo-db/sse-specification
    :portkey.cloudformation.dynamo-db/table-name
    :portkey.cloudformation.dynamo-db/global-secondary-indexes]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.dynamo-db/table-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.dynamo-db/index-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.dynamo-db/global-secondary-index
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.dynamo-db/index-name
    :portkey.cloudformation.dynamo-db/key-schema
    :portkey.cloudformation.dynamo-db/projection
    :portkey.cloudformation.dynamo-db/provisioned-throughput]
   :opt
   [])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.dynamo-db/index-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.dynamo-db/local-secondary-index
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.dynamo-db/index-name
    :portkey.cloudformation.dynamo-db/key-schema
    :portkey.cloudformation.dynamo-db/projection]
   :opt
   [])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.dynamo-db/attribute-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.dynamo-db/attribute-type
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.dynamo-db/attribute-definition
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.dynamo-db/attribute-name
    :portkey.cloudformation.dynamo-db/attribute-type]
   :opt
   [])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.dynamo-db/read-capacity-units
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.dynamo-db/write-capacity-units
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.dynamo-db/provisioned-throughput
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.dynamo-db/read-capacity-units
    :portkey.cloudformation.dynamo-db/write-capacity-units]
   :opt
   [])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.dynamo-db/attribute-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.dynamo-db/key-type
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.dynamo-db/key-schema
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.dynamo-db/attribute-name
    :portkey.cloudformation.dynamo-db/key-type]
   :opt
   [])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.dynamo-db/attribute-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.dynamo-db/enabled
  (portkey.cloudformation/ref-or-spec clojure.core/boolean?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.dynamo-db/time-to-live-specification
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.dynamo-db/attribute-name
    :portkey.cloudformation.dynamo-db/enabled]
   :opt
   [])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.dynamo-db/projection-type
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.dynamo-db/projection
  (clojure.spec.alpha/keys
   :req
   []
   :opt
   [:portkey.cloudformation.dynamo-db/non-key-attributes
    :portkey.cloudformation.dynamo-db/projection-type])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.dynamo-db/sse-enabled
  (portkey.cloudformation/ref-or-spec clojure.core/boolean?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.dynamo-db/sse-specification
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.dynamo-db/sse-enabled]
   :opt
   [])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.dynamo-db/stream-view-type
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.dynamo-db/stream-specification
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.dynamo-db/stream-view-type]
   :opt
   [])))
