(ns portkey.cloudformation.ecs
  "AUTOGENERATED clojure.spec definitions"
  (:require [clojure.spec.alpha]
            [portkey.cloudformation]))

(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.ecs/service
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.ecs/task-definition]
   :opt
   [:portkey.cloudformation.ecs/placement-strategies
    :portkey.cloudformation.ecs/desired-count
    :portkey.cloudformation.ecs/deployment-configuration
    :portkey.cloudformation.ecs/role
    :portkey.cloudformation.ecs/load-balancers
    :portkey.cloudformation.ecs/cluster
    :portkey.cloudformation.ecs/network-configuration
    :portkey.cloudformation.ecs/platform-version
    :portkey.cloudformation.ecs/service-name
    :portkey.cloudformation.ecs/launch-type
    :portkey.cloudformation.ecs/placement-constraints
    :portkey.cloudformation.ecs/health-check-grace-period-seconds]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/desired-count
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/role
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/cluster
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/task-definition
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/platform-version
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/service-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/launch-type
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/health-check-grace-period-seconds
  (portkey.cloudformation/ref-or-spec clojure.core/integer?)))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.ecs/cluster
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id :portkey.cloudformation/type]
   :opt
   [:portkey.cloudformation.ecs/cluster-name]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/cluster-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.ecs/task-definition
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id :portkey.cloudformation/type]
   :opt
   [:portkey.cloudformation.ecs/cpu
    :portkey.cloudformation.ecs/task-role-arn
    :portkey.cloudformation.ecs/family
    :portkey.cloudformation.ecs/execution-role-arn
    :portkey.cloudformation.ecs/memory
    :portkey.cloudformation.ecs/requires-compatibilities
    :portkey.cloudformation.ecs/network-mode
    :portkey.cloudformation.ecs/placement-constraints
    :portkey.cloudformation.ecs/volumes
    :portkey.cloudformation.ecs/container-definitions]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/cpu
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/task-role-arn
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/family
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/execution-role-arn
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/memory
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/network-mode
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/hard-limit
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/soft-limit
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/ulimit
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.ecs/hard-limit
    :portkey.cloudformation.ecs/name
    :portkey.cloudformation.ecs/soft-limit]
   :opt
   [])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/value
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/key-value-pair
  (clojure.spec.alpha/keys
   :req
   []
   :opt
   [:portkey.cloudformation.ecs/name
    :portkey.cloudformation.ecs/value])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/maximum-percent
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/minimum-healthy-percent
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/deployment-configuration
  (clojure.spec.alpha/keys
   :req
   []
   :opt
   [:portkey.cloudformation.ecs/maximum-percent
    :portkey.cloudformation.ecs/minimum-healthy-percent])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/network-configuration
  (clojure.spec.alpha/keys
   :req
   []
   :opt
   [:portkey.cloudformation.ecs/awsvpc-configuration])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/hostname
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/ip-address
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/host-entry
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.ecs/hostname
    :portkey.cloudformation.ecs/ip-address]
   :opt
   [])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/container-path
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/host-path
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/device
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.ecs/host-path]
   :opt
   [:portkey.cloudformation.ecs/container-path
    :portkey.cloudformation.ecs/permissions])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/source-path
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/host-volume-properties
  (clojure.spec.alpha/keys
   :req
   []
   :opt
   [:portkey.cloudformation.ecs/source-path])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/kernel-capabilities
  (clojure.spec.alpha/keys
   :req
   []
   :opt
   [:portkey.cloudformation.ecs/add :portkey.cloudformation.ecs/drop])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/assign-public-ip
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/aws-vpc-configuration
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.ecs/subnets]
   :opt
   [:portkey.cloudformation.ecs/assign-public-ip
    :portkey.cloudformation.ecs/security-groups])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/expression
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/type
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/placement-constraint
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.ecs/type]
   :opt
   [:portkey.cloudformation.ecs/expression])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/container-port
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/host-port
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/protocol
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/port-mapping
  (clojure.spec.alpha/keys
   :req
   []
   :opt
   [:portkey.cloudformation.ecs/container-port
    :portkey.cloudformation.ecs/host-port
    :portkey.cloudformation.ecs/protocol])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/cpu
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/user
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/privileged
  (portkey.cloudformation/ref-or-spec clojure.core/boolean?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/hostname
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/disable-networking
  (portkey.cloudformation/ref-or-spec clojure.core/boolean?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/memory
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/readonly-root-filesystem
  (portkey.cloudformation/ref-or-spec clojure.core/boolean?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/image
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/essential
  (portkey.cloudformation/ref-or-spec clojure.core/boolean?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/working-directory
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/memory-reservation
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/container-definition
  (clojure.spec.alpha/keys
   :req
   []
   :opt
   [:portkey.cloudformation.ecs/docker-security-options
    :portkey.cloudformation.ecs/volumes-from
    :portkey.cloudformation.ecs/cpu
    :portkey.cloudformation.ecs/port-mappings
    :portkey.cloudformation.ecs/user
    :portkey.cloudformation.ecs/privileged
    :portkey.cloudformation.ecs/log-configuration
    :portkey.cloudformation.ecs/hostname
    :portkey.cloudformation.ecs/disable-networking
    :portkey.cloudformation.ecs/environment
    :portkey.cloudformation.ecs/command
    :portkey.cloudformation.ecs/entry-point
    :portkey.cloudformation.ecs/linux-parameters
    :portkey.cloudformation.ecs/memory
    :portkey.cloudformation.ecs/ulimits
    :portkey.cloudformation.ecs/readonly-root-filesystem
    :portkey.cloudformation.ecs/extra-hosts
    :portkey.cloudformation.ecs/image
    :portkey.cloudformation.ecs/name
    :portkey.cloudformation.ecs/docker-labels
    :portkey.cloudformation.ecs/essential
    :portkey.cloudformation.ecs/working-directory
    :portkey.cloudformation.ecs/mount-points
    :portkey.cloudformation.ecs/dns-servers
    :portkey.cloudformation.ecs/memory-reservation
    :portkey.cloudformation.ecs/links
    :portkey.cloudformation.ecs/dns-search-domains])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/container-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/container-port
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/load-balancer-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/target-group-arn
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/load-balancer
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.ecs/container-port]
   :opt
   [:portkey.cloudformation.ecs/container-name
    :portkey.cloudformation.ecs/load-balancer-name
    :portkey.cloudformation.ecs/target-group-arn])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/expression
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/type
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/task-definition-placement-constraint
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.ecs/type]
   :opt
   [:portkey.cloudformation.ecs/expression])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/field
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/type
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/placement-strategy
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.ecs/type]
   :opt
   [:portkey.cloudformation.ecs/field])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/read-only
  (portkey.cloudformation/ref-or-spec clojure.core/boolean?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/source-container
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/volume-from
  (clojure.spec.alpha/keys
   :req
   []
   :opt
   [:portkey.cloudformation.ecs/read-only
    :portkey.cloudformation.ecs/source-container])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/volume
  (clojure.spec.alpha/keys
   :req
   []
   :opt
   [:portkey.cloudformation.ecs/host
    :portkey.cloudformation.ecs/name])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/log-driver
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/log-configuration
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.ecs/log-driver]
   :opt
   [:portkey.cloudformation.ecs/options])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/container-path
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/read-only
  (portkey.cloudformation/ref-or-spec clojure.core/boolean?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/source-volume
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/mount-point
  (clojure.spec.alpha/keys
   :req
   []
   :opt
   [:portkey.cloudformation.ecs/container-path
    :portkey.cloudformation.ecs/read-only
    :portkey.cloudformation.ecs/source-volume])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/init-process-enabled
  (portkey.cloudformation/ref-or-spec clojure.core/boolean?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.ecs/linux-parameters
  (clojure.spec.alpha/keys
   :req
   []
   :opt
   [:portkey.cloudformation.ecs/capabilities
    :portkey.cloudformation.ecs/devices
    :portkey.cloudformation.ecs/init-process-enabled])))
