(ns portkey.cloudformation.iam
  "AUTOGENERATED clojure.spec definitions"
  (:require [clojure.spec.alpha]
            [portkey.cloudformation]))

(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.iam/user
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id :portkey.cloudformation/type]
   :opt
   [:portkey.cloudformation.iam/groups
    :portkey.cloudformation.iam/login-profile
    :portkey.cloudformation.iam/managed-policy-arns
    :portkey.cloudformation.iam/path
    :portkey.cloudformation.iam/policies
    :portkey.cloudformation.iam/user-name]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/path
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/user-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.iam/group
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id :portkey.cloudformation/type]
   :opt
   [:portkey.cloudformation.iam/group-name
    :portkey.cloudformation.iam/managed-policy-arns
    :portkey.cloudformation.iam/path
    :portkey.cloudformation.iam/policies]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/group-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/path
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.iam/instance-profile
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.iam/roles]
   :opt
   [:portkey.cloudformation.iam/instance-profile-name
    :portkey.cloudformation.iam/path]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/instance-profile-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/path
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.iam/policy
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.iam/policy-document
    :portkey.cloudformation.iam/policy-name]
   :opt
   [:portkey.cloudformation.iam/groups
    :portkey.cloudformation.iam/roles
    :portkey.cloudformation.iam/users]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/policy-document
  (portkey.cloudformation/ref-or-spec clojure.core/any?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/policy-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.iam/managed-policy
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.iam/policy-document]
   :opt
   [:portkey.cloudformation.iam/description
    :portkey.cloudformation.iam/groups
    :portkey.cloudformation.iam/managed-policy-name
    :portkey.cloudformation.iam/path
    :portkey.cloudformation.iam/roles
    :portkey.cloudformation.iam/users]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/description
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/managed-policy-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/path
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/policy-document
  (portkey.cloudformation/ref-or-spec clojure.core/any?)))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.iam/role
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.iam/assume-role-policy-document]
   :opt
   [:portkey.cloudformation.iam/managed-policy-arns
    :portkey.cloudformation.iam/path
    :portkey.cloudformation.iam/policies
    :portkey.cloudformation.iam/role-name]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/assume-role-policy-document
  (portkey.cloudformation/ref-or-spec clojure.core/any?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/path
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/role-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.iam/access-key
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.iam/user-name]
   :opt
   [:portkey.cloudformation.iam/serial
    :portkey.cloudformation.iam/status]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/serial
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/status
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/user-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.iam/user-to-group-addition
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.iam/group-name
    :portkey.cloudformation.iam/users]
   :opt
   []))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/group-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/policy-document
  (portkey.cloudformation/ref-or-spec clojure.core/any?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/policy-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/policy
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.iam/policy-document
    :portkey.cloudformation.iam/policy-name]
   :opt
   [])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/password
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/password-reset-required
  (portkey.cloudformation/ref-or-spec clojure.core/boolean?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/login-profile
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.iam/password]
   :opt
   [:portkey.cloudformation.iam/password-reset-required])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/policy-document
  (portkey.cloudformation/ref-or-spec clojure.core/any?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/policy-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/policy
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.iam/policy-document
    :portkey.cloudformation.iam/policy-name]
   :opt
   [])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/policy-document
  (portkey.cloudformation/ref-or-spec clojure.core/any?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/policy-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.iam/policy
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.iam/policy-document
    :portkey.cloudformation.iam/policy-name]
   :opt
   [])))
