(ns portkey.cloudformation.rds
  "AUTOGENERATED clojure.spec definitions"
  (:require [clojure.spec.alpha]
            [portkey.cloudformation]))

(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.rds/event-subscription
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.rds/sns-topic-arn]
   :opt
   [:portkey.cloudformation.rds/enabled
    :portkey.cloudformation.rds/event-categories
    :portkey.cloudformation.rds/source-ids
    :portkey.cloudformation.rds/source-type]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/enabled
  (portkey.cloudformation/ref-or-spec clojure.core/boolean?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/sns-topic-arn
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/source-type
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.rds/db-instance
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.rds/db-instance-class]
   :opt
   [:portkey.cloudformation.rds/backup-retention-period
    :portkey.cloudformation.rds/option-group-name
    :portkey.cloudformation.rds/db-security-groups
    :portkey.cloudformation.rds/character-set-name
    :portkey.cloudformation.rds/publicly-accessible
    :portkey.cloudformation.rds/source-region
    :portkey.cloudformation.rds/domain-iam-role-name
    :portkey.cloudformation.rds/preferred-maintenance-window
    :portkey.cloudformation.rds/copy-tags-to-snapshot
    :portkey.cloudformation.rds/db-instance-identifier
    :portkey.cloudformation.rds/auto-minor-version-upgrade
    :portkey.cloudformation.rds/tags
    :portkey.cloudformation.rds/db-name
    :portkey.cloudformation.rds/vpc-security-groups
    :portkey.cloudformation.rds/availability-zone
    :portkey.cloudformation.rds/master-user-password
    :portkey.cloudformation.rds/license-model
    :portkey.cloudformation.rds/domain
    :portkey.cloudformation.rds/allow-major-version-upgrade
    :portkey.cloudformation.rds/allocated-storage
    :portkey.cloudformation.rds/source-db-instance-identifier
    :portkey.cloudformation.rds/monitoring-interval
    :portkey.cloudformation.rds/timezone
    :portkey.cloudformation.rds/master-username
    :portkey.cloudformation.rds/engine-version
    :portkey.cloudformation.rds/db-snapshot-identifier
    :portkey.cloudformation.rds/storage-encrypted
    :portkey.cloudformation.rds/db-subnet-group-name
    :portkey.cloudformation.rds/port
    :portkey.cloudformation.rds/kms-key-id
    :portkey.cloudformation.rds/iops
    :portkey.cloudformation.rds/storage-type
    :portkey.cloudformation.rds/engine
    :portkey.cloudformation.rds/db-parameter-group-name
    :portkey.cloudformation.rds/monitoring-role-arn
    :portkey.cloudformation.rds/multi-az
    :portkey.cloudformation.rds/db-cluster-identifier
    :portkey.cloudformation.rds/preferred-backup-window]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/backup-retention-period
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/option-group-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/character-set-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/publicly-accessible
  (portkey.cloudformation/ref-or-spec clojure.core/boolean?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/source-region
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/domain-iam-role-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/preferred-maintenance-window
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/copy-tags-to-snapshot
  (portkey.cloudformation/ref-or-spec clojure.core/boolean?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/db-instance-identifier
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/auto-minor-version-upgrade
  (portkey.cloudformation/ref-or-spec clojure.core/boolean?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/db-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/availability-zone
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/master-user-password
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/license-model
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/domain
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/allow-major-version-upgrade
  (portkey.cloudformation/ref-or-spec clojure.core/boolean?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/allocated-storage
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/source-db-instance-identifier
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/monitoring-interval
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/timezone
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/master-username
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/engine-version
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/db-snapshot-identifier
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/storage-encrypted
  (portkey.cloudformation/ref-or-spec clojure.core/boolean?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/db-subnet-group-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/port
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/kms-key-id
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/iops
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/storage-type
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/db-instance-class
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/engine
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/db-parameter-group-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/monitoring-role-arn
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/multi-az
  (portkey.cloudformation/ref-or-spec clojure.core/boolean?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/db-cluster-identifier
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/preferred-backup-window
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.rds/db-security-group-ingress
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.rds/db-security-group-name]
   :opt
   [:portkey.cloudformation.rds/cidrip
    :portkey.cloudformation.rds/ec2-security-group-id
    :portkey.cloudformation.rds/ec2-security-group-name
    :portkey.cloudformation.rds/ec2-security-group-owner-id]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/cidrip
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/db-security-group-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/ec2-security-group-id
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/ec2-security-group-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/ec2-security-group-owner-id
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.rds/db-security-group
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.rds/db-security-group-ingress
    :portkey.cloudformation.rds/group-description]
   :opt
   [:portkey.cloudformation.rds/ec2-vpc-id
    :portkey.cloudformation.rds/tags]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/ec2-vpc-id
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/group-description
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.rds/db-subnet-group
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.rds/db-subnet-group-description
    :portkey.cloudformation.rds/subnet-ids]
   :opt
   [:portkey.cloudformation.rds/db-subnet-group-name
    :portkey.cloudformation.rds/tags]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/db-subnet-group-description
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/db-subnet-group-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.rds/option-group
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.rds/engine-name
    :portkey.cloudformation.rds/major-engine-version
    :portkey.cloudformation.rds/option-configurations
    :portkey.cloudformation.rds/option-group-description]
   :opt
   [:portkey.cloudformation.rds/tags]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/engine-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/major-engine-version
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/option-group-description
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.rds/db-cluster-parameter-group
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.rds/description
    :portkey.cloudformation.rds/family
    :portkey.cloudformation.rds/parameters]
   :opt
   [:portkey.cloudformation.rds/tags]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/description
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/family
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/parameters
  (portkey.cloudformation/ref-or-spec clojure.core/any?)))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.rds/db-parameter-group
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.rds/description
    :portkey.cloudformation.rds/family]
   :opt
   [:portkey.cloudformation.rds/parameters
    :portkey.cloudformation.rds/tags]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/description
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/family
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.rds/db-cluster
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.rds/engine]
   :opt
   [:portkey.cloudformation.rds/snapshot-identifier
    :portkey.cloudformation.rds/backup-retention-period
    :portkey.cloudformation.rds/replication-source-identifier
    :portkey.cloudformation.rds/database-name
    :portkey.cloudformation.rds/preferred-maintenance-window
    :portkey.cloudformation.rds/tags
    :portkey.cloudformation.rds/vpc-security-group-ids
    :portkey.cloudformation.rds/db-cluster-parameter-group-name
    :portkey.cloudformation.rds/master-user-password
    :portkey.cloudformation.rds/master-username
    :portkey.cloudformation.rds/engine-version
    :portkey.cloudformation.rds/storage-encrypted
    :portkey.cloudformation.rds/db-subnet-group-name
    :portkey.cloudformation.rds/port
    :portkey.cloudformation.rds/kms-key-id
    :portkey.cloudformation.rds/availability-zones
    :portkey.cloudformation.rds/db-cluster-identifier
    :portkey.cloudformation.rds/preferred-backup-window]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/snapshot-identifier
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/backup-retention-period
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/replication-source-identifier
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/database-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/preferred-maintenance-window
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/db-cluster-parameter-group-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/master-user-password
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/master-username
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/engine-version
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/storage-encrypted
  (portkey.cloudformation/ref-or-spec clojure.core/boolean?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/db-subnet-group-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/port
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/kms-key-id
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/engine
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/db-cluster-identifier
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/preferred-backup-window
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/cidrip
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/ec2-security-group-id
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/ec2-security-group-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/ec2-security-group-owner-id
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/ingress
  (clojure.spec.alpha/keys
   :req
   []
   :opt
   [:portkey.cloudformation.rds/cidrip
    :portkey.cloudformation.rds/ec2-security-group-id
    :portkey.cloudformation.rds/ec2-security-group-name
    :portkey.cloudformation.rds/ec2-security-group-owner-id])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/option-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/option-version
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/port
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/option-configuration
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.rds/option-name]
   :opt
   [:portkey.cloudformation.rds/db-security-group-memberships
    :portkey.cloudformation.rds/option-settings
    :portkey.cloudformation.rds/option-version
    :portkey.cloudformation.rds/port
    :portkey.cloudformation.rds/vpc-security-group-memberships])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/value
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.rds/option-setting
  (clojure.spec.alpha/keys
   :req
   []
   :opt
   [:portkey.cloudformation.rds/name
    :portkey.cloudformation.rds/value])))
