(ns portkey.cloudformation.redshift
  "AUTOGENERATED clojure.spec definitions"
  (:require [clojure.spec.alpha]
            [portkey.cloudformation]))

(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.redshift/cluster-security-group-ingress
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.redshift/cluster-security-group-name]
   :opt
   [:portkey.cloudformation.redshift/cidrip
    :portkey.cloudformation.redshift/ec2-security-group-name
    :portkey.cloudformation.redshift/ec2-security-group-owner-id]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/cidrip
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/cluster-security-group-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/ec2-security-group-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/ec2-security-group-owner-id
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.redshift/cluster-subnet-group
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.redshift/description
    :portkey.cloudformation.redshift/subnet-ids]
   :opt
   [:portkey.cloudformation.redshift/tags]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/description
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.redshift/cluster-security-group
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.redshift/description]
   :opt
   [:portkey.cloudformation.redshift/tags]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/description
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.redshift/cluster
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.redshift/db-name
    :portkey.cloudformation.redshift/cluster-type
    :portkey.cloudformation.redshift/master-user-password
    :portkey.cloudformation.redshift/master-username
    :portkey.cloudformation.redshift/node-type]
   :opt
   [:portkey.cloudformation.redshift/snapshot-identifier
    :portkey.cloudformation.redshift/publicly-accessible
    :portkey.cloudformation.redshift/logging-properties
    :portkey.cloudformation.redshift/preferred-maintenance-window
    :portkey.cloudformation.redshift/encrypted
    :portkey.cloudformation.redshift/owner-account
    :portkey.cloudformation.redshift/hsm-client-certificate-identifier
    :portkey.cloudformation.redshift/cluster-identifier
    :portkey.cloudformation.redshift/cluster-subnet-group-name
    :portkey.cloudformation.redshift/number-of-nodes
    :portkey.cloudformation.redshift/tags
    :portkey.cloudformation.redshift/vpc-security-group-ids
    :portkey.cloudformation.redshift/availability-zone
    :portkey.cloudformation.redshift/cluster-security-groups
    :portkey.cloudformation.redshift/elastic-ip
    :portkey.cloudformation.redshift/hsm-configuration-identifier
    :portkey.cloudformation.redshift/port
    :portkey.cloudformation.redshift/kms-key-id
    :portkey.cloudformation.redshift/allow-version-upgrade
    :portkey.cloudformation.redshift/cluster-version
    :portkey.cloudformation.redshift/automated-snapshot-retention-period
    :portkey.cloudformation.redshift/iam-roles
    :portkey.cloudformation.redshift/snapshot-cluster-identifier
    :portkey.cloudformation.redshift/cluster-parameter-group-name]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/snapshot-identifier
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/publicly-accessible
  (portkey.cloudformation/ref-or-spec clojure.core/boolean?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/preferred-maintenance-window
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/encrypted
  (portkey.cloudformation/ref-or-spec clojure.core/boolean?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/owner-account
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/hsm-client-certificate-identifier
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/cluster-identifier
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/cluster-subnet-group-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/number-of-nodes
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/db-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/availability-zone
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/cluster-type
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/master-user-password
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/elastic-ip
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/master-username
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/hsm-configuration-identifier
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/port
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/kms-key-id
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/allow-version-upgrade
  (portkey.cloudformation/ref-or-spec clojure.core/boolean?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/cluster-version
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/automated-snapshot-retention-period
  (portkey.cloudformation/ref-or-spec clojure.core/integer?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/node-type
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/snapshot-cluster-identifier
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/cluster-parameter-group-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.redshift/cluster-parameter-group
  [___19567__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation/id
    :portkey.cloudformation/type
    :portkey.cloudformation.redshift/description
    :portkey.cloudformation.redshift/parameter-group-family]
   :opt
   [:portkey.cloudformation.redshift/parameters
    :portkey.cloudformation.redshift/tags]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/description
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/parameter-group-family
  (portkey.cloudformation/ref-or-spec clojure.core/string?)))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/bucket-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/s3-key-prefix
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/logging-properties
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.redshift/bucket-name]
   :opt
   [:portkey.cloudformation.redshift/s3-key-prefix])))
(do
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/parameter-name
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/parameter-value
  (portkey.cloudformation/ref-or-spec clojure.core/string?))
 (clojure.spec.alpha/def
  :portkey.cloudformation.redshift/parameter
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.redshift/parameter-name
    :portkey.cloudformation.redshift/parameter-value]
   :opt
   [])))
