(ns portkey.cloudformation.work-spaces
  "AUTOGENERATED clojure.spec definitions"
  (:require [clojure.spec.alpha]
            [portkey.cloudformation]))

(do
 (clojure.core/defmethod
  portkey.cloudformation/resource-type-spec
  :portkey.cloudformation.work-spaces/workspace
  [___15594__auto__]
  (clojure.spec.alpha/keys
   :req
   [:portkey.cloudformation.work-spaces/bundle-id
    :portkey.cloudformation.work-spaces/directory-id
    :portkey.cloudformation.work-spaces/user-name]
   :opt
   [:portkey.cloudformation.work-spaces/root-volume-encryption-enabled
    :portkey.cloudformation.work-spaces/user-volume-encryption-enabled
    :portkey.cloudformation.work-spaces/volume-encryption-key]))
 (clojure.spec.alpha/def
  :portkey.cloudformation.work-spaces/bundle-id
  clojure.core/string?)
 (clojure.spec.alpha/def
  :portkey.cloudformation.work-spaces/directory-id
  clojure.core/string?)
 (clojure.spec.alpha/def
  :portkey.cloudformation.work-spaces/root-volume-encryption-enabled
  clojure.core/boolean?)
 (clojure.spec.alpha/def
  :portkey.cloudformation.work-spaces/user-name
  clojure.core/string?)
 (clojure.spec.alpha/def
  :portkey.cloudformation.work-spaces/user-volume-encryption-enabled
  clojure.core/boolean?)
 (clojure.spec.alpha/def
  :portkey.cloudformation.work-spaces/volume-encryption-key
  clojure.core/string?))
